import { Merchant, User, Transaction, TicketValidation, DashboardStats } from '../types';

export const INITIAL_MERCHANT: Merchant = {
  id: 'm-noparchi-001',
  businessName: 'Metro Hub Smart Parking',
  location: 'Connaught Place, New Delhi',
  upiId: 'metrohub@icici',
  configSettings: {
    twoWheelerRate: 20,
    fourWheelerRate: 50,
    flatRate: 40,
    currency: 'INR',
    enableWhatsApp: true,
    businessLogo: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=128&auto=format&fit=crop&q=80',
    themeColor: '#10B981',
    welcomeMessage: 'Thank you for parking with Metro Hub! Show this QR at exit gate.',
  },
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updatedAt: new Date().toISOString(),
};

export const INITIAL_USERS: User[] = [
  {
    id: 'u-owner-001',
    merchantId: 'm-noparchi-001',
    isOwner: true,
    phone: '+91 98765 43210',
    name: 'Rajesh Sharma (Owner)',
    passcode: '1234',
    permission: {
      userId: 'u-owner-001',
      can_view_ledger: true,
      can_verify_tickets: true,
      can_edit_settings: true,
      can_issue_refund: true,
    },
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'u-staff-001',
    merchantId: 'm-noparchi-001',
    isOwner: false,
    phone: '+91 98111 22233',
    name: 'Amit Kumar (Gate 1 Staff)',
    passcode: '0000',
    permission: {
      userId: 'u-staff-001',
      can_view_ledger: false,
      can_verify_tickets: true,
      can_edit_settings: false,
      can_issue_refund: false,
    },
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'u-staff-002',
    merchantId: 'm-noparchi-001',
    isOwner: false,
    phone: '+91 98222 33344',
    name: 'Vikas Singh (Gate 2 Supervisor)',
    passcode: '1111',
    permission: {
      userId: 'u-staff-002',
      can_view_ledger: true,
      can_verify_tickets: true,
      can_edit_settings: false,
      can_issue_refund: true,
    },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const now = Date.now();
const hour = 3600 * 1000;
const day = 24 * hour;

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    merchantId: 'm-noparchi-001',
    amount: 50,
    vehicleNumber: 'DL 01 AB 1234',
    vehicleType: 'FOUR_WHEELER',
    status: 'SUCCESS',
    paymentRef: 'UPI-982347101',
    customerPhone: '+91 99887 76655',
    ticketCode: 'NP-A7X1-K892',
    qrPayload: JSON.stringify({
      app: 'NoParchi',
      ticketCode: 'NP-A7X1-K892',
      merchantId: 'm-noparchi-001',
      amount: 50,
      vehicleNumber: 'DL 01 AB 1234',
      issuedAt: new Date(now - 45 * 60 * 1000).toISOString(),
    }),
    createdAt: new Date(now - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 45 * 60 * 1000).toISOString(),
    validation: {
      id: 'val-001',
      transactionId: 'tx-001',
      scannedByUserId: 'u-staff-001',
      scannedByUser: {
        id: 'u-staff-001',
        name: 'Amit Kumar',
        phone: '+91 98111 22233',
      },
      timestamp: new Date(now - 10 * 60 * 1000).toISOString(),
      exitGate: 'Exit Gate 1',
      notes: 'Customer passed without issues',
    },
  },
  {
    id: 'tx-002',
    merchantId: 'm-noparchi-001',
    amount: 20,
    vehicleNumber: 'DL 04 CD 5678',
    vehicleType: 'TWO_WHEELER',
    status: 'SUCCESS',
    paymentRef: 'UPI-982347102',
    customerPhone: '+91 98765 11223',
    ticketCode: 'NP-B8Y2-M341',
    qrPayload: JSON.stringify({
      app: 'NoParchi',
      ticketCode: 'NP-B8Y2-M341',
      merchantId: 'm-noparchi-001',
      amount: 20,
      vehicleNumber: 'DL 04 CD 5678',
      issuedAt: new Date(now - 30 * 60 * 1000).toISOString(),
    }),
    createdAt: new Date(now - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 30 * 60 * 1000).toISOString(),
    validation: null, // Active ticket, ready to scan!
  },
  {
    id: 'tx-003',
    merchantId: 'm-noparchi-001',
    amount: 50,
    vehicleNumber: 'HR 26 DQ 9999',
    vehicleType: 'FOUR_WHEELER',
    status: 'SUCCESS',
    paymentRef: 'UPI-982347103',
    customerPhone: '+91 91234 56780',
    ticketCode: 'NP-C9Z3-P452',
    qrPayload: JSON.stringify({
      app: 'NoParchi',
      ticketCode: 'NP-C9Z3-P452',
      merchantId: 'm-noparchi-001',
      amount: 50,
      vehicleNumber: 'HR 26 DQ 9999',
      issuedAt: new Date(now - 20 * 60 * 1000).toISOString(),
    }),
    createdAt: new Date(now - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 20 * 60 * 1000).toISOString(),
    validation: null, // Active ticket, ready to scan!
  },
  {
    id: 'tx-004',
    merchantId: 'm-noparchi-001',
    amount: 100,
    vehicleNumber: 'UP 16 ER 4455',
    vehicleType: 'HEAVY_VEHICLE',
    status: 'SUCCESS',
    paymentRef: 'UPI-982347104',
    customerPhone: '+91 99112 33445',
    ticketCode: 'NP-D1W4-Q783',
    qrPayload: JSON.stringify({
      app: 'NoParchi',
      ticketCode: 'NP-D1W4-Q783',
      merchantId: 'm-noparchi-001',
      amount: 100,
      vehicleNumber: 'UP 16 ER 4455',
      issuedAt: new Date(now - 15 * 60 * 1000).toISOString(),
    }),
    createdAt: new Date(now - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 15 * 60 * 1000).toISOString(),
    validation: null, // Active ticket
  },
  {
    id: 'tx-005',
    merchantId: 'm-noparchi-001',
    amount: 20,
    vehicleNumber: 'DL 09 GH 7788',
    vehicleType: 'TWO_WHEELER',
    status: 'SUCCESS',
    paymentRef: 'UPI-982347105',
    customerPhone: '+91 98991 22334',
    ticketCode: 'NP-E2V5-R904',
    qrPayload: JSON.stringify({
      app: 'NoParchi',
      ticketCode: 'NP-E2V5-R904',
      merchantId: 'm-noparchi-001',
      amount: 20,
      vehicleNumber: 'DL 09 GH 7788',
      issuedAt: new Date(now - 1 * day).toISOString(),
    }),
    createdAt: new Date(now - 1 * day).toISOString(),
    updatedAt: new Date(now - 1 * day).toISOString(),
    validation: {
      id: 'val-005',
      transactionId: 'tx-005',
      scannedByUserId: 'u-staff-002',
      timestamp: new Date(now - 1 * day + 2 * hour).toISOString(),
      exitGate: 'Exit Gate 2',
    },
  },
  {
    id: 'tx-006',
    merchantId: 'm-noparchi-001',
    amount: 50,
    vehicleNumber: 'HR 51 JK 2345',
    vehicleType: 'FOUR_WHEELER',
    status: 'SUCCESS',
    paymentRef: 'UPI-982347106',
    customerPhone: '+91 97110 98765',
    ticketCode: 'NP-F3U6-S015',
    createdAt: new Date(now - 2 * day).toISOString(),
    updatedAt: new Date(now - 2 * day).toISOString(),
    validation: {
      id: 'val-006',
      transactionId: 'tx-006',
      scannedByUserId: 'u-staff-001',
      timestamp: new Date(now - 2 * day + 1 * hour).toISOString(),
      exitGate: 'Exit Gate 1',
    },
  },
];
